---
title: "Gene regulatory networks: a primer in biological processes and statistical modelling"
subtitle: "Gene Regulatory Networks - Humana Press"
description: "Review on gene expression regulation and Gene Regulatory Networks modelling"
author: "Olivia Angelin-Bonnet, Patrick J. Biggs, Matthieu Vignes"
date: "2019-01-01"
categories: [GRN, modelling]
---

- DOI: <https://doi.org/10.1007/978-1-4939-8882-2_15>
- Preprint: <https://arxiv.org/abs/1805.01098>

## Abstract

Modelling gene regulatory networks requires not only a thorough understanding of the biological system depicted, but also the ability to accurately represent this system from a mathematical perspective. Throughout this chapter, we aim to familiarize the reader with the biological processes and molecular factors at play in the process of gene expression regulation. We first describe the different interactions controlling each step of the expression process, from transcription to mRNA and protein decay. In the second section, we provide statistical tools to accurately represent this biological complexity in the form of mathematical models. Among other considerations, we discuss the topological properties of biological networks, the application of deterministic and stochastic frameworks, and the quantitative modelling of regulation. We particularly focus on the use of such models for the simulation of expression data that can serve as a benchmark for the testing of network inference algorithms.

## Cite us

> Angelin-Bonnet, O., Biggs, P. J., & Vignes, M. (2019). Gene regulatory networks: a primer in biological processes and statistical modelling. In *Gene Regulatory Networks* (pp. 347-383). Humana Press, New York, NY.
 https://doi.org/10.1007/978-1-4939-8882-2_15

Or with bibtex:

```
@inbook{Angelin-Bonnet2019,
	title        = {Gene Regulatory Networks: A Primer in Biological Processes and Statistical Modelling},
	author       = {Angelin-Bonnet, Olivia and Biggs, Patrick J. and Vignes, Matthieu},
	year         = 2019,
	booktitle    = {Gene Regulatory Networks: Methods and Protocols },
	publisher    = {Springer New York},
	address      = {New York, NY},
	pages        = {347--383},
	doi          = {10.1007/978-1-4939-8882-2_15},
	isbn         = {978-1-4939-8882-2},
	url          = {https://doi.org/10.1007/978-1-4939-8882-2_15},
	editor       = {Sanguinetti, Guido and Huynh-Thu, V{\^a}n Anh}
}
```
