project:
  type: website

website:
  title: "Olivia Angelin-Bonnet"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - blog.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

