project:
  type: website
  preview:
    port: 1234
    browser: true

website:
  title: "Olivia Angelin-Bonnet"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - talks.qmd
      - projects.qmd
      - blog.qmd

format:
  html:
    theme: [cosmo, styles.scss]
    toc: true

editor: visual

